"""3rd migration

Revision ID: 0a5d05fc4e08
Revises: 2d04ec2fda90
Create Date: 2019-05-02 15:00:11.508293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5d05fc4e08'
down_revision = '2d04ec2fda90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('posted', sa.DateTime(), nullable=True))
    op.add_column('questions', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'posted')
    op.drop_column('answers', 'posted')
    # ### end Alembic commands ###
