"""empty message

Revision ID: 2d04ec2fda90
Revises: 22f335ce1e50
Create Date: 2019-05-02 12:41:15.108056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d04ec2fda90'
down_revision = '22f335ce1e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'comment')
    # ### end Alembic commands ###
