"""empty message

Revision ID: 4e66839fc88f
Revises: 269af9a6ddfd
Create Date: 2019-05-02 12:10:30.226594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e66839fc88f'
down_revision = '269af9a6ddfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('votes_userid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'votes_userid')
    # ### end Alembic commands ###
